import createWorkerRenderer from "./createWorkerRenderer.js";

export { rendererConfig } from "./config.js";

// Sync (main-thread) renderers
export { default as arrowField } from "./arrowField.js";
export { default as asciiMosaic } from "./asciiMosaic.js";
export { default as barSwap } from "./barSwap.js";
export { default as circlePacking } from "./circlePacking.js";
export { default as crosshatch } from "./crosshatch.js";
export { default as echo } from "./echo.js";
export { default as glitch } from "./glitch.js";
export { default as gridSwap } from "./gridSwap.js";
export { default as halftone } from "./halftone.js";
export { default as kaleidoscope } from "./kaleidoscope.js";
export { default as lightLeak } from "./lightLeak.js";
export { default as lowPoly } from "./lowPoly.js";
export { default as pixelated } from "./pixelated.js";
export { default as radialBlur } from "./radialBlur.js";
export { default as scooch } from "./scooch.js";
export { default as smear } from "./smear.js";
export { default as stacked } from "./stacked.js";
export { default as stackedCircle } from "./stackedCircle.js";
export { default as subdivision } from "./subdivision.js";

// Async (worker-backed) renderers
export const angularBlur = createWorkerRenderer("angularBlur");
export const barShift = createWorkerRenderer("barShift");
export const bokehBlur = createWorkerRenderer("bokehBlur");
export const bulge = createWorkerRenderer("bulge");
export const chalkboard = createWorkerRenderer("chalkboard");
export const channelBlur = createWorkerRenderer("channelBlur");
export const chromaticAberration = createWorkerRenderer("chromaticAberration");
export const compression = createWorkerRenderer("compression");
export const concentricSpin = createWorkerRenderer("concentricSpin");
export const contourLines = createWorkerRenderer("contourLines");
export const crt = createWorkerRenderer("crt");
export const dataMosh = createWorkerRenderer("dataMosh");
export const diffuseBlur = createWorkerRenderer("diffuseBlur");
export const dither = createWorkerRenderer("dither");
export const duotone = createWorkerRenderer("duotone");
export const emboss = createWorkerRenderer("emboss");
export const engraving = createWorkerRenderer("engraving");
export const filmGrain = createWorkerRenderer("filmGrain");
export const flutedGlass = createWorkerRenderer("flutedGlass");
export const glassTiles = createWorkerRenderer("glassTiles");
export const glow = createWorkerRenderer("glow");
export const gradientMap = createWorkerRenderer("gradientMap");
export const lensDistortion = createWorkerRenderer("lensDistortion");
export const melt = createWorkerRenderer("melt");
export const mirror = createWorkerRenderer("mirror");
export const motionMask = createWorkerRenderer("motionMask");
export const neonEdge = createWorkerRenderer("neonEdge");
export const oilPaint = createWorkerRenderer("oilPaint");
export const paperPrint = createWorkerRenderer("paperPrint");
export const photocopy = createWorkerRenderer("photocopy");
export const pixelSort = createWorkerRenderer("pixelSort");
export const polar = createWorkerRenderer("polar");
export const posterize = createWorkerRenderer("posterize");
export const risograph = createWorkerRenderer("risograph");
export const ripple = createWorkerRenderer("ripple");
export const sketch = createWorkerRenderer("sketch");
export const solarize = createWorkerRenderer("solarize");
export const spiral = createWorkerRenderer("spiral");
export const tiltShift = createWorkerRenderer("tiltShift");
export const velocityBlur = createWorkerRenderer("velocityBlur");
export const vhs = createWorkerRenderer("vhs");
export const watercolor = createWorkerRenderer("watercolor");
export const waves = createWorkerRenderer("waves");
